<?php 
/**
 * TL_ROOT/system/modules/cron/languages/de/modules.php 
 * 
 * TYPOlight extension: cron 1.0.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2007, 2008, 2009 
 * License   : GNU GPL V2 
 * Author    : Peter Koch (acenes), http://ibk-software.com 
 * Translator: Peter Koch (acenes), http://ibk-software.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['cron']['0'] = "Scheduler";
$GLOBALS['TL_LANG']['MOD']['cron']['1'] = "Ein Cron-ähnliches Scheduler-Modul für Contao";
 
